import typing

def pad_embedding(embedding: list[float], target_dim: int = 3072) -> list[float]:
    """Pad or truncate embedding vector to target dimensionality"""
    if not embedding:
        return embedding
    if len(embedding) < target_dim:
        return list(embedding) + [0.0] * (target_dim - len(embedding))
    elif len(embedding) > target_dim:
        return embedding[:target_dim]
    return embedding

def strip_json_fences(text: str) -> str:
    """Remove markdown formatting from JSON output generated by LLMs."""
    content = text.strip()
    if content.startswith("```json"):
        content = content[7:]
    elif content.startswith("```"):
        content = content[3:]
    if content.endswith("```"):
        content = content[:-3]
    return content.strip()

def extract_api_keys(headers: dict, fallback_dict: dict = None) -> dict:
    """Extract api keys from headers, fallback to body dictionary"""
    # normalize headers to lowercase
    headers = {k.lower(): v for k, v in headers.items()}
    fallback = fallback_dict or {}
    
    return {
        "gemini": headers.get("x-gemini-key") or fallback.get("gemini"),
        "mistral": headers.get("x-mistral-key") or fallback.get("mistral"),
        "firecrawl": headers.get("x-firecrawl-key") or fallback.get("firecrawl"),
        "lingodev": headers.get("x-lingodev-key") or fallback.get("lingodev"),
        "groq": headers.get("x-groq-key") or fallback.get("groq"),
        "openai": headers.get("x-openai-key") or fallback.get("openai"),
        "hf": headers.get("x-hf-token") or fallback.get("hf")
    }
