import typing

def pad_embedding(embedding: list[float], target_dim: int = 3072) -> list[float]:
    """Pad or truncate embedding vector to target dimensionality"""
    if not embedding:
        return embedding
    if len(embedding) < target_dim:
        return list(embedding) + [0.0] * (target_dim - len(embedding))
    elif len(embedding) > target_dim:
        return embedding[:target_dim]
    return embedding

def strip_json_fences(text: str) -> str:
    """Remove markdown formatting from JSON output generated by LLMs."""
    content = text.strip()
    if content.startswith("```json"):
        content = content[7:]
    elif content.startswith("```"):
        content = content[3:]
    if content.endswith("```"):
        content = content[:-3]
    return content.strip()

def extract_api_keys(headers: dict, fallback_dict: dict = None) -> dict:
    """Extract api keys from headers, fallback to body dictionary"""
    return {
        "x-mistral-key": headers.get("x-mistral-key"),
        "x-gemini-key": headers.get("x-gemini-key"),
        "x-firecrawl-key": headers.get("x-firecrawl-key"),
        "x-apify-token": headers.get("x-apify-token"),
    }

def is_mostly_non_ascii(s):
    if not s: return False
    threshold = len(s) * 0.2
    non_ascii = 0
    for c in s:
        if ord(c) > 127:
            non_ascii += 1
            if non_ascii > threshold:
                return True
    return False

def normalize_url(url: str) -> str:
    """Normalize URL for consistent storage. Preserves query strings (e.g. YouTube ?v=...)."""
    try:
        from urllib.parse import urlparse, urlunparse
        parsed = urlparse(url)
        # Rebuild URL: keep scheme, netloc, stripped path, params, query, and NO fragment
        normalized = urlunparse((
            parsed.scheme,
            parsed.netloc,
            parsed.path.rstrip('/'),
            parsed.params,
            parsed.query,   # IMPORTANT: preserve query string (e.g. ?v=xxxx for YouTube)
            ''              # strip fragment (#anchor)
        ))
        return normalized
    except:
        return url

LANG_MAP = {
    "en": "English",
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "it": "Italian",
    "ja": "Japanese",
    "zh": "Chinese",
    "pt": "Portuguese",
    "ru": "Russian",
    "ko": "Korean"
}
